[general]
email = "mat.major1@gmail.com"

[OPENAI_API_KEY]
OPENAI_API_KEY = "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"  # Your actual OpenAI key here
